# SPDX-FileCopyrightText: 2025 The Project Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: my-app
description: A simple Flask app Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"