# SPDX-FileCopyrightText: 2025 The Project Authors
# SPDX-License-Identifier: Apache-2.0

replicaCount: 1

image:
  repository: demo/simple-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

container:
  port: 5000

resources: {}

ingress:
  enabled: false